k230 sdk release v1.7

diff --git a/src/common/cdk/kernel/ipcm/do_make_module b/src/common/cdk/kernel/ipcm/do_make_module
--- a/src/common/cdk/kernel/ipcm/do_make_module
+++ b/src/common/cdk/kernel/ipcm/do_make_module
@@ -43,6 +43,38 @@ ipcm_clean:
 	else \
 		echo "os: error parameter!!"; \
 	fi
+	
+virt_tty:
+ifdef VIRT_TTY_ROLE
+	@echo "virt_tty real make"
+	@echo ${CROSS_COMPILE}
+	if [ ${OS_TYPE} = "linux" ]; then \
+		make -C ${PWD}/class/virt-tty/linux/ all || exit 1; \
+		make -C ${PWD}/class/virt-tty/app/ all; \
+	elif [ ${OS_TYPE} = "rtsmart" ]; then \
+		cd ${PWD}/class/virt-tty/rt-smart/; \
+		make -f ${PWD}/class/virt-tty/rt-smart/Makefile all; \
+		cd -; \
+	else \
+		echo "os: error parameter!!"; \
+	fi
+endif
+
+virt_tty_clean:
+ifdef VIRT_TTY_ROLE
+	@echo "virt_tty make clean"
+	@echo ${CROSS_COMPILE}
+	if [ ${OS_TYPE} = "linux" ];then \
+		make -C ${PWD}/class/virt-tty/linux/ clean; \
+		make -C ${PWD}/class/virt-tty/app/ clean; \
+	elif [ ${OS_TYPE} = "rtsmart" ]; then \
+		cd ${PWD}/class/virt-tty/rt-smart; \
+		make -f ${PWD}/class/virt-tty/rt-smart/Makefile clean; \
+		cd -; \
+	else \
+		echo "os: error parameter!!"; \
+	fi
+endif
 
 sharefs:
 ifdef SHAREFS
@@ -77,3 +109,29 @@ ifeq ($(SHAREFS), y)
 	fi
 endif
 endif
+
+rtt_ctrl:
+	@echo "rtt_ctrl real make"
+	@echo ${CROSS_COMPILE}
+	if [ ${OS_TYPE} = "linux" ]; then \
+		make -C ${PWD}/class/rtt-ctrl/linux/ all || exit 1; \
+	elif [ ${OS_TYPE} = "rtsmart" ]; then \
+		cd ${PWD}/class/rtt-ctrl/rt-smart/; \
+		make -f ${PWD}/class/rtt-ctrl/rt-smart/Makefile all; \
+		cd -; \
+	else \
+		echo "os: error parameter!!"; \
+	fi
+
+rtt_ctrl_clean:
+	@echo "rtt_ctrl make clean"
+	@echo ${CROSS_COMPILE}
+	if [ ${OS_TYPE} = "linux" ];then \
+		make -C ${PWD}/class/rtt-ctrl/linux/ clean; \
+	elif [ ${OS_TYPE} = "rtsmart" ]; then \
+		cd ${PWD}/class/rtt-ctrl/rt-smart; \
+		make -f ${PWD}/class/rtt-ctrl/rt-smart/Makefile clean; \
+		cd -; \
+	else \
+		echo "os: error parameter!!"; \
+	fi
